@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

Person(teacher, "Teacher")
Person(student, "Student")
Person(company, "Company")
Person(external, "External Person")

System_Boundary(koble, "Koble") {
  Container(api, "Koble API", "Spring Boot", "REST API")
  ContainerDb(db, "Database", "MySQL", "Dados do sistema")
}

Rel(teacher, api, "Usa", "HTTP/JSON")
Rel(student, api, "Usa", "HTTP/JSON")
Rel(company, api, "Usa", "HTTP/JSON")
Rel(external, api, "Usa", "HTTP/JSON")
Rel(api, db, "Lê/Escreve", "JDBC")

@enduml
