@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

Person(teacher, "Teacher")
Person(student, "Student")
Person(company, "Company")
Person(external, "External Person")

System_Boundary(koble, "Koble") {
  Container_Boundary(api, "Koble API") {
    Component(controllers, "Controllers", "Spring MVC", "Endpoints REST")
    Component(daos, "DAOs", "JDBC", "Acesso ao banco")
    Component(models, "Models", "Java", "POJOs de domínio")
  }
  ContainerDb(db, "Database", "MySQL", "Dados do sistema")
}

Rel(teacher, controllers, "Usa", "HTTP/JSON")
Rel(student, controllers, "Usa", "HTTP/JSON")
Rel(company, controllers, "Usa", "HTTP/JSON")
Rel(external, controllers, "Usa", "HTTP/JSON")

Rel(controllers, daos, "Usa")
Rel(daos, db, "Lê/Escreve", "JDBC")

@enduml
